
global gBlockSecsPerTick

%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%% Plot Waves %%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%

% figure('units','normalized','outerposition',[0 0 1 1],'Name',...
%     'Waveform of different Channels');
% groupPlot(capturedData(:,1:6),timeBase,[3,2],1:6,...
%     {'Seconds'},{'Voltage (\muV)'}, strcat('Waveform of raw ',...
%     {' O_1' ' O_2' ' P_3' ' P_4' ' O_z' ' P_z'},' Channel'));
%
figure('units','normalized','outerposition',[0 0 1 1],'Name',...
    'Spectrum of different Channels');
quickSpect(capturedData(:,1:6),[3 2],50000,1000,[4 20],...
    'Freq [Hz]','Voltage (\muV)',strcat('Spectrum of raw ',...
    {' O_1' ' O_2' ' P_3' ' P_4' ' O_z' ' P_z'},' Channel'));
%
% figure('units','normalized','outerposition',[0 0 1 1],'Name',...
%     'Waveform of Correlated U');
% groupPlot(U,timeBase,[3,2],1:6,...
%     {'Seconds'},{'Voltage (\muV)'},strcat('Waveform of Correlated Wave U ',...
%     {' O_1' ' O_2' ' P_3' ' P_4' ' O_z' ' P_z'},' Channel'));
%
% figure('units','normalized','outerposition',[0 0 1 1],'Name',...
%     'Spectrum of Correlated U');
% quickSpect(U,[3 2],5000,1000,[4 20],...
%     'Freq [Hz]','Voltage (\muV)',strcat('Spectrum of Correlated Wave U ',...
%     {' O_1' ' O_2' ' P_3' ' P_4' ' O_z' ' P_z'},' Channel'));
%
% figure('units','normalized','outerposition',[0 0 1 1],'Name',...
%     'Waveform of Correlated V');
% groupPlot(V,timeBase,[3,2],1:6,...
%     {'Seconds'},{'Voltage (\muV)'},strcat('Waveform of Correlated Wave V ',...
%     {' O_1' ' O_2' ' P_3' ' P_4' ' O_z' ' P_z'},' Channel'));
%
% figure('units','normalized','outerposition',[0 0 1 1],'Name',...
%     'Spectrum of Correlated V');
% quickSpect(V,[3 2],5000,1000,[4 20],...
%     'Freq [Hz]','Voltage (\muV)',strcat('Spectrum of Correlated Wave V ',...
%     {' O_1' ' O_2' ' P_3' ' P_4' ' O_z' ' P_z'},' Channel'));